name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - uses: eskatos/gradle-command-action@v1
        with:
            arguments: build
      - uses: actions/upload-artifacts@v2
        with:
          name: windows-binaries
          path: |
            emotion-standalone/build/bin/mingwX64/compileReleaseExecutable/emotionc.exe
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - uses: eskatos/gradle-command-action@v1
        with:
            arguments: build
